apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug
  namespace: ops-debug
spec:
  selector:
    matchLabels: { app: debug }
  template:
    metadata:
      labels: { app: debug }
    spec:
      hostNetwork: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      containers:
        - name: shell
          image: alpine:3.20
          command: ["/bin/sh","-c","sleep infinity"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: hostfs
              mountPath: /host
      volumes:
        - name: hostfs
          hostPath: { path: / }
