apiVersion: v1
kind: Secret
metadata:
    name: minio-user-paperless
    namespace: rag-system
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:7hdIsgC2qYFSyLVBpEyz/4ZmF9PupG5E/E6JB14trpVDJXAndxc3ivekXjc=,iv:E/2o3HpWgUH2l2b+Xd4+o+m8wQLvcntP32XVt6Erdhw=,tag:4k9BL3y+JxzJzcadoU3srQ==,type:str]
sops:
    age:
        - recipient: age1p26qk2kerzdf0dj705ergv7smregn6tfy02yxwhmmdv4ldh2vqaqxvpz3t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2U3ZMekFlRGNEeUQ2aU9R
            WCtveTEvaEZ0dnExUUVmUzVhOFdmUHNLeVJFCk5PZmtNa1MxTjJvRnFJQWU1OWZJ
            RHJEZDBqQVBmRWorRGRsbVRSOG83MlEKLS0tIDduTVpCMEhscmg4RUhXak11UHpk
            SU96alUrdkZnMlJXZndTdDV4RDYvN28KEyB4tVkqbommeer/wMKLiQkb+nQNB7fK
            iSCGASw3bQzVezaxIgT9PbIKoAk3y9fCwLI8MzO4NoSdV2Dy3gGzEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T10:06:35Z"
    mac: ENC[AES256_GCM,data:Eqka1I7xPIW5Q2byhduH8FTKZ73Dt2R/kiTTzkPHrUx91HnnzDr9toHoJo1QaBHfOW8KhnGRzB0z3oyWrzMwF3a5W3jwAmLbNAXchh0o6XTPonm1J9SeIA5GtC/333QmuRGLfP3ZPqd/bg7RRBcaJsCi8TgdDUWe5RxDbG/hoBM=,iv:Ivy04iEidBfc8jGUH581X/FO/Z+R80//Li7EFRkRfpQ=,tag:SwM3SSkwCmw2atty4ULY6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
