apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: rag-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: '0.22.x'
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: rag-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Resource limits for Raspberry Pi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Monitoring (enable later when Prometheus is deployed)
    monitoring:
      podMonitorEnabled: false
