# Traefik Ingress Controller - Managed by Flux
# This HelmRelease tells Flux to install and manage Traefik
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: traefik
      version: "33.2.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  install:
    crds: CreateReplace
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  # Reference the values from the existing file
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      valuesKey: values.yaml
