# n8n Workflow Automation - Managed by Flux
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: n8n
      version: "1.15.12"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  # Reference the values from ConfigMap
  valuesFrom:
    - kind: ConfigMap
      name: n8n-values
      valuesKey: values.yaml
