apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - namespace.yaml
  - values-configmap.yaml
  - helmrelease.yaml
  - ingress-external.yaml
  - network-policy.yaml
