# Cloudflare Tunnel - Managed by Flux
# This HelmRelease tells Flux to install and manage cloudflared
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ./charts/cloudflared
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  # Values inline since they're small
  values:
    replicaCount: 2
    image:
      repository: cloudflare/cloudflared
      tag: "2024.10.0"
      pullPolicy: IfNotPresent
    tunnel:
      secretName: cloudflare-tunnel-token
      secretKey: token
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
