apiVersion: batch/v1
kind: Job
metadata:
  name: paperless-db-init
  namespace: rag-system
spec:
  ttlSecondsAfterFinished: 300  # Clean up after 5 minutes
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: paperless-db-init
      containers:
        - name: init-db
          image: bitnami/kubectl:latest
          env:
            - name: PAPERLESS_USER
              valueFrom:
                secretKeyRef:
                  name: paperless-db-credentials
                  key: username
            - name: PAPERLESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-db-credentials
                  key: password
          command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Creating paperless database and user..."

              # Execute commands directly in the postgres pod (no remote auth needed)

              # Create user if not exists
              kubectl exec -n rag-system postgres-rag-1 -- psql -U postgres -c "
                DO \$\$
                BEGIN
                  IF NOT EXISTS (SELECT FROM pg_user WHERE usename = '${PAPERLESS_USER}') THEN
                    CREATE USER ${PAPERLESS_USER} WITH PASSWORD '${PAPERLESS_PASSWORD}';
                  END IF;
                END
                \$\$;"

              # Create database if not exists (check first to avoid error)
              DB_EXISTS=$(kubectl exec -n rag-system postgres-rag-1 -- psql -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname='paperless'")
              if [ -z "$DB_EXISTS" ]; then
                kubectl exec -n rag-system postgres-rag-1 -- psql -U postgres -c "CREATE DATABASE paperless OWNER ${PAPERLESS_USER};"
              else
                echo "Database paperless already exists, skipping creation"
              fi

              # Grant privileges
              kubectl exec -n rag-system postgres-rag-1 -- psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE paperless TO ${PAPERLESS_USER};"

              echo "Database initialization complete"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paperless-db-init
  namespace: rag-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paperless-db-init
  namespace: rag-system
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paperless-db-init
  namespace: rag-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paperless-db-init
subjects:
  - kind: ServiceAccount
    name: paperless-db-init
    namespace: rag-system
