# Let's Encrypt Staging ClusterIssuer
# Use for testing - staging API has higher rate limits
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Staging server - use for testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email for expiration notifications
    email: your-email@example.com  # TODO: Replace with actual email

    # Private key secret for ACME account
    privateKeySecretRef:
      name: letsencrypt-staging-account-key

    # HTTP-01 challenge solver
    solvers:
    - http01:
        ingress:
          class: traefik
