# Applications Kustomization
# This tells Flux to deploy all applications AFTER infrastructure is ready
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/talos/apps
  prune: false  # Disabled to prevent conflicts with Helm-managed resources
  wait: false
