# Infrastructure Kustomization
# This tells Flux to deploy all core infrastructure components
# Dependencies: None (deployed first)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/talos/infrastructure
  prune: true
  wait: true
